version: 2
sources:
  - name: raw_311
    description: Raw data loaded from NYC Open Data
    database: preston-cis-9440-s26
    schema: final_project_raw_sr
    tables:
      - name: source_service_request
        description: |
          311 Service Requests from 2020 to Present.
          One row per service request.
        columns:
          - name: address_type
            description: Type of incident location information available.
          - name: agency
            description: Acronym of responding City Government Agency
          - name: agency_name
            description: Full Agency name of responding City Government Agency
          - name: bbl
            description: Borough Block and Lot, provided by geovalidation. Parcel number to identify the location of location of buildings and properties in NYC.
          - name: borough
            description: Provided by the submitter and confirmed by geovalidation.
          - name: city
            description: City of the incident location provided by geovalidation.
          - name: closed_date
            description: Date SR was closed by responding agency
          - name: community_board
            description: Provided by geovalidation. 
          - name: complaint_type
            description: This is the first level of a hierarchy identifying the topic of the incident or condition. Problem (formerly Complaint Type) broadly describes the topic of the incident or condition and are defined by the responding agencies. New Problems may be added in response to changes in customer demand.
          - name: council_district
            description: The City Council district where the service request is located.
          - name: created_date
            description: Date SR was created
          - name: cross_street_1
            description: First Cross street based on the geo validated incident location
          - name: cross_street_2
            description: Second Cross Street based on the geo validated incident location
          - name: descriptor
            description: This is associated to the Problem (formerly Complaint Type), and provides further detail on the incident or condition. Problem Detail (formerly Descriptor) values are dependent on the Problem, and are not always required in the service request.
          - name: descriptor_2
            description: A third level of detail about the Problem (formerly Complaint Type) beyond the Problem Detail (formerly Descriptor). This is not used by every category of issue.
          #due_date would go here, but all data pulled didn't have anything in this column
          - name: incident_address
            description: House number of incident address provided by submitter.
          - name: incident_zip
            description: Incident location zip code, provided by geo validation.
          - name: intersection_street_1
            description: First intersecting street based on geo validated incident location
          - name: intersection_street_2
            description: Second intersecting street based on geo validated incident location
          - name: landmark
            description: If the incident location is identified as a Landmark the name of the landmark will display here
          - name: latitude
            description: Geo based Lat of the incident location
          #location would go here, but as it is geospatial "Point" data it wasn't captured by a table
          - name: location_type
            description: Describes the type of location used in the address information
          - name: longitude
            description: Geo based Long of the incident location
          - name: open_data_channel_type
            description: Indicates how the SR was submitted to 311. i.e. By Phone, Online, Mobile, Other or Unknown.
          - name: park_borough
            description: The borough of incident if it is a Parks Dept facility
          - name: park_facility_name
            description: If the incident location is a Parks Dept facility, the Name of the facility will appear here
          - name: police_precinct
            description: The NYPD precinct where the service request is located.
          - name: resolution_action_updated_date
            description: Date when responding agency last updated the SR.
          - name: resolution_description
            description: Describes the last action taken on the SR by the responding agency. May describe next or future steps.
          #road_ramp returned no data
          - name: status
            description: Status of SR submitted
          - name: street_name
            description: Street name of incident address provided by the submitter
          #variables with no data:
          #taxi_company_borough
          #taxi_pick_up_location
          #vehicle_type
          - name: unique_key
            description: Unique ID for the service request
            tests:
              - unique
              - not_null
          - name: x_coordinate_state_plane
            description: Geo validated, X coordinate of the incident location.
          - name: y_coordinate_state_plane
            description: Geo validated, Y coordinate of the incident location.
          - name: facility_type
            description: If available, this field describes the type of city facility associated to the SR
          


  - name: raw_inspections
    description: Raw data loaded from NYC Open Data
    database: preston-cis-9440-s26
    schema: final_project_raw_ci
    tables:
      - name: source_cafeteria_inspections
        description: |
          DOHMH School Cafeteria Inspections (2020-Present)
          One row per application. Note: original dataset may have two or more entries for the same restaurant.
        columns:
          - name: bbl
            description: Borough-Block-Lot
          - name: bin
            description: Building Identification Number
          - name: borocode
            description: Numerical code for the borough of establishment (school) location
          - name: borough
            description: Borough of establishment (school) location
          - name: censustract
            description: Census Tract
          - name: city
            description: Municipality of establishment (school)
          - name: code
            description: Violation code associated with inspection finding; Blank field indicates no violations were cited during inspection
          - name: communityboard
            description: Community Board
          - name: councildistrict
            description: NYC Council District
          - name: entityid
            description: Unique identifier for the establishment (school)
            tests:
              - unique
              - not_null
          - name: inspectiondate
            description: Date an inspection was conducted
          - name: lastinspection
            description: Date of last inspection
          - name: latitude
            description: Latitude
          - name: level
            description: Indicator of the type of violation; Critical violations are those most likely to contribute to foodborne illness.
          - name: longitude
            description: Longitude
          - name: nta
            description: Neighborhood Tabulation Area
          - name: number
            description: Building number for establishment (school) location
          - name: permittee
            description: Name of business owner holding the permit
          - name: ptet
            description: Permit Type Establishment Type - The four digit code indicating the type of permit and the type of food service establishment (FSE)
          - name: schoolname
            description: Establishment (school) name
          - name: site_type
            description: The description of the type of food service establishment (FSE)
          - name: state
            description: State of establishment (school)
          - name: street
            description: Street name for establishment (school) location
          - name: violationdescription
            description: Violation description associated with inspection finding; Blank field indicates no violations were cited during inspection
          - name: zipcode
            description: Zip code of establishment (school) location